Repository AiursoftWeb/Kahla, pull requests merged in 2019-06, with the labels that each got.

#89 API for adding kick-out members
  Kahla.Server/Controllers/GroupsController.cs
  Kahla.Server/Events/KahlaEvent.cs
  Kahla.Server/Services/KahlaPushService.cs
Labels: new feature

#94 Fix bugs that cause 500 error messages to be returned when kicking
  Kahla.Server/Controllers/GroupsController.cs
  Kahla.Server/Events/KahlaEvent.cs
  Kahla.Server/Services/KahlaPushService.cs
Labels: bug

#101 Release 3.5.0.
  Kahla.Server/Controllers/AuthController.cs
  Kahla.Server/Controllers/ConversationController.cs
  Kahla.Server/Controllers/DevicesController.cs
  Kahla.Server/Controllers/FilesController.cs
  Kahla.Server/Controllers/FriendshipController.cs
  Kahla.Server/Controllers/GroupsController.cs
  Kahla.Server/Events/KahlaEvent.cs
  Kahla.Server/Kahla.Server.csproj
  Kahla.Server/Models/ApiAddressModels/AllAddressModel.cs
  Kahla.Server/Models/ApiAddressModels/UpdateGroupAddressModel.cs
  Kahla.Server/Models/ApiAddressModels/UpdateGroupPasswordAddressModel.cs
  Kahla.Server/Models/ApiViewModels/FriendDiscovery.cs
  Kahla.Server/Models/ApiViewModels/MineViewModel.cs
  Kahla.Server/Models/ApiViewModels/SearchedGroup.cs
  Kahla.Server/Models/GroupConversation.cs
  Kahla.Server/Models/PrivateConversation.cs
  Kahla.Server/Services/KahlaPushService.cs
  Kahla.Server/web.config
Labels: new feature

#102 Hotfix 3.5.0 production release.
  Kahla.Server/Controllers/ConversationController.cs
  Kahla.Server/Controllers/FriendshipController.cs
  Kahla.Server/Data/KahlaDbContext.cs
  Kahla.Server/Models/ApiAddressModels/AllAddressModel.cs
  Kahla.Server/Models/ApiViewModels/ContactInfo.cs
  Kahla.Server/Models/GroupConversation.cs
  Kahla.Server/Models/PrivateConversation.cs
Labels: bug

#103 3.5.1
  Kahla.Server/Controllers/ConversationController.cs
  Kahla.Server/Controllers/DevicesController.cs
  Kahla.Server/Controllers/GroupsController.cs
Labels: new feature

#106 Delete lots of fucking code
  Kahla.Server/Controllers/GroupsController.cs
  Kahla.Server/Models/ApiAddressModels/UpdateGroupAddressModel.cs
  Kahla.Server/Services/OwnerChecker.cs
  Kahla.Server/Startup.cs
Labels: enhancement
